In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4])
x = np.array([True,False,True,False])
newArr = a[x]
print(newArr)

[1 3]


In [3]:
arr = np.array([41,42,43,44])
filter_array = []
for x in arr:
    if x>41:
        filter_array.append(True)
    else:
        filter_array.append(False)
newArr = arr[filter_array]
print(filter_array)
print(newArr)

[False, True, True, True]
[42 43 44]


In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9])
filter_array1 = []
for x in arr:
    if x%2==0:
        filter_array1.append(True)
    else:
        filter_array1.append(False)
newArr = arr[filter_array1]
print(filter_array1)
print(newArr)

[False, True, False, True, False, True, False, True, False]
[2 4 6 8]


In [5]:
filter_arr = arr%2==0
newArr= arr[filter_arr]
print(filter_arr)
print(newArr)

[False  True False  True False  True False  True False]
[2 4 6 8]
