In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4,5])
arr[1:5]

array([2, 3, 4, 5])

In [4]:
arr[-3:-1]

array([3, 4])

In [6]:
arr[1:5:2]

array([2, 4])

In [10]:
arr[::2]

array([1, 3, 5])

In [11]:
## slicing 2-D array
arr1 = np.array([[1,2,3],[4,5,6]])

In [12]:
arr1.ndim

2

In [26]:
arr1[0:2,2]

array([3, 6])