In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
## Tuple with 1-D array
arr1 = np.array((1,2,3,4,5))
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
## 0-D array
arr2 = np.array(42)
arr2

array(42)

In [10]:
## 2-D array
arr3 = np.array(([1,2,3],[4,5,6]))
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
## 3-D array
arr4 = np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])

In [21]:
arr4.ndim

3

In [26]:
arr5 = np.array([1,2,3,4,5],ndmin=4)
print(arr5)

[[[[1 2 3 4 5]]]]


In [25]:
arr5.ndim

4