In [1]:
import numpy as np



In [13]:
arr = np.array(('array','python','dataScience'),dtype='S')
print(arr.dtype)

|S11


In [20]:
arr1 =  np.array((11,22,34,45),dtype='int')
arr1.dtype

dtype('int64')

In [28]:
## float to integer conversion
arr2 = np.array((1.2,3.4,5.6,7.8))
print(arr2)
print(arr2.dtype)
newArr = arr2.astype(int)
print(newArr)
print(newArr.dtype)

[1.2 3.4 5.6 7.8]
float64
[1 3 5 7]
int64


In [31]:
## integer to boolean
Arr = np.array([0,1,2])
newArr_1 = Arr.astype(bool)
newArr_1

array([False,  True,  True])