In [1]:
import numpy as np


In [15]:
arr = np.array((1,2,3,4,0,7,7,5,4))
x = np.searchsorted(arr,4)
print(x)

5


In [5]:
arr1 = np.array((1,2,3,4,5,2,3,4))
x = np.where(arr==4)

In [6]:
x

(array([3, 8]),)

In [14]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


## Sorting

In [2]:
import numpy as np
arr2 = np.array((1,4,5,2,3,7,8,4,5,9))
np.sort(arr2)

array([1, 2, 3, 4, 4, 5, 5, 7, 8, 9])

In [3]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [4]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [5]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
