In [2]:
import numpy as np

In [6]:
arr = np.array((1,2,3,4))
newArr = np.split(arr,2)   ## if array index is out of range this split will through an error
newArr

[array([1, 2]), array([3, 4])]

In [9]:
## advance version of split---->array_split()
newArr_1 = np.array_split(arr,5)
newArr_1

[array([1]), array([2]), array([3]), array([4]), array([], dtype=int64)]

In [19]:
## splitting 2-D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr1)
newArr_2 = np.array_split(arr1,3)
newArr_2

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

## split 2-D array with 2-D array along with rows

In [23]:
newArr_3 = np.array_split(arr1,3,axis=1)
newArr_3

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [25]:
## using hsplit which is opposite of hstack
newArr_4  = np.hsplit(arr1,3)
newArr_4

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]