In [1]:
import numpy as np

In [7]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
newArr = np.concatenate((arr_1,arr_2),axis = 0)


In [5]:
newArr

array([1, 2, 3, 4, 5, 6])

In [12]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [21]:
arr = np.stack((arr1,arr2),axis=1)
arr

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [22]:
hstac = np.hstack((arr1,arr2))
hstac

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [24]:
vstac = np.vstack((arr1,arr2))
vstac

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## stacking along height using dstack

In [25]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)


[[[1 4]
  [2 5]
  [3 6]]]
