In [1]:
import numpy as np



## copies owns the data but views does not own the data

In [2]:
arr =  np.array((1,2,3,4))
x = arr.copy()
arr[0]= 42
print(arr)
print(x)

[42  2  3  4]
[1 2 3 4]


In [3]:
arr =  np.array((1,2,3,4))
x = arr.view()
arr[0]= 42
print(arr)
print(x)

[42  2  3  4]
[42  2  3  4]


## Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [4]:
arr_1 = np.array((1,2,3,4,5))
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)


None
[42  2  3  4]
