In [1]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)    ## shuffle methods makes changes to the original array
print(arr)

[2 5 1 3 4]


In [11]:
print(np.random.permutation(arr)) ##permutation method returns a re-arranged array while leaves the original array

[5 1 2 4 3]


In [12]:
arr

array([2, 5, 1, 3, 4])