In [2]:
from numpy import random


In [24]:
x = random.randint(100)  ## it will generate a random integer between 1 to 100
x

40

In [10]:
x = random.rand()
x

0.4140863232685572

In [15]:
## generate random array
x = random.randint(100,size=(3,5))
x


array([[24,  8, 43, 36, 38],
       [ 5, 99, 73, 26, 94],
       [85, 57, 97, 88, 21]])

In [18]:
x = random.rand(3,5)
x

array([[0.07036114, 0.88623309, 0.75927815, 0.20946903, 0.54211922],
       [0.97887033, 0.11089132, 0.44410484, 0.36902791, 0.50297728],
       [0.80620189, 0.35063908, 0.88798152, 0.23033787, 0.06476147]])

In [19]:
## random number from array
x = random.choice([3,4,5,6],size=(3,5))
x


array([[4, 6, 5, 3, 6],
       [4, 6, 3, 4, 6],
       [6, 4, 6, 6, 3]])