## Ufuncs 
# stands for Universal function and they are numpy functions that operate on the ndarray object

In [1]:
## without ufunc, use zip() method
a = [1,2,3,4]
b = [5,6,7,8]
c = []
for i,j in zip(a,b):
    c.append(i+j)
print(c)

[6, 8, 10, 12]


In [3]:
## with ufunc, use add() function
import numpy as np
c = np.add(a,b)
print(c)

[ 6  8 10 12]


## ufunc create function


In [6]:
def myadd(a,b):
    return a+b

myadd = np.frompyfunc(myadd,2,1)
print(myadd([1,2,3,4],[5,6,7,8]))

[6 8 10 12]


In [11]:
if type(np.add)==np.ufunc:
    print('add is ufunc')
if type(np.add)!=np.ufunc:
    print('add is not ufunc')

add is ufunc


In [12]:
d = np.divide(a,b)
d

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [13]:
## power function
a = [10,5,2,3]
b = [2,3,2,3]
newarr = np.power(a,b)
newarr

array([100, 125,   4,  27])

In [17]:
newarr = np.mod(a,b)    ## it will return the remainder----> both remainder and mod function will return the remainder
print(newarr)
newarr_1 = np.remainder(a,b)
print(newarr_1)

[0 2 0 0]
[0 2 0 0]


In [18]:
## quotient and mod
### divmod() return the quotient and mode value, first array represents the quotient and the second array represents the mod
a = [10,20,30,40,50,60]
b = [3,4,5,6,7,8]
c = np.divmod(a,b)
c

(array([3, 5, 6, 6, 7, 7]), array([1, 0, 0, 4, 1, 4]))

In [23]:
## absolute values
a = np.array([-1,-2,-3,1,2,3,-4])
b = np.absolute(a)    
c = abs(a)
print(b)
print(c)

[1 2 3 1 2 3 4]
[1 2 3 1 2 3 4]


## rounding decimals

1. remove the decimals and return float number closet to zero. use trunc() and fix() functions.

In [26]:
arr = np.array([-1.5567,1.5678])

arr_1 = np.trunc(arr)
print(arr_1)
arr_2 = np.fix(arr)
print(arr_2)

[-1.  1.]
[-1.  1.]


## around()
1.function increases by 1 if value decimal value is greater than 5

In [28]:
arr = np.around(3.2666,2)
print(arr)

3.27


## floor() function
1. floor function round off decimal to nearest lower integer

In [31]:
arr = np.floor([-3.1667,3.66])
arr

array([-4.,  3.])

## ceil() function

In [32]:
arr = np.ceil([-3.166,3.434])
arr

array([-3.,  4.])

## logs

In [36]:
arr = np.arange(1,10)
print(np.log2(arr))
print(np.log10(arr))
print(np.log(arr))


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


## summation

In [38]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])

newarr = np.sum([arr1,arr2])
newarr

12

In [40]:
## summation over axis
newarr_1 = np.sum([arr1,arr2],axis=1)
newarr_1

array([6, 6])

In [41]:
arr3 = np.array([1,2,3,4])
newarr_2 = np.cumsum(arr3)
newarr_2

array([ 1,  3,  6, 10])

## products

In [44]:
x = np.prod(arr3)
x

24

In [45]:
y = np.prod([arr1,arr2])
y

36

In [47]:
## product over an axis
z = np.prod([arr1,arr2],axis=1)
z

array([6, 6])

In [49]:
## cummulative product
l = np.cumprod(arr3)
l

array([ 1,  2,  6, 24])

In [50]:
## discreate difference
newarr = np.diff(arr3)
newarr

array([1, 1, 1])

In [51]:
## discreate difference twice
newarr = np.diff(arr3,n=2)
newarr

array([0, 0])

## LCM


In [55]:
num1 = 4
num2 = 6

x = np.lcm(num1,num2)
x

12

In [54]:
arr = np.array([3,6,9])
x = np.lcm.reduce(arr)
x

18

## GCD

In [56]:
num1 = 6
num2 = 9
x = np.gcd(num1,num2)
x


3

In [57]:
a = np.array([24,28,20,8,16])
x = np.gcd.reduce(a)
x

4

## Trigonometric

In [58]:
arr = np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])
newarr = np.sin(arr)
newarr

array([1.        , 0.8660254 , 0.70710678, 0.58778525])

In [59]:
arr = np.array([90,180,270,360])
x  =np.deg2rad(arr)
x

array([1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [60]:
arr = np.array([np.pi/2,np.pi,1.5*np.pi])
x = np.rad2deg(arr)
x

array([ 90., 180., 270.])

In [63]:
x = np.arcsin(1)
print(np.rad2deg(x))

90.0


In [64]:
x = np.arctan(1)
print(np.rad2deg(x))

45.0


## hypotenues using pythogoras theorem

In [65]:
base = 3
height = 4
x = np.hypot(base,height)
x

5.0

## set operations

In [66]:
arr = np.array([1,1,1,2,3,4,5,1,2,3,4])
x = np.unique(arr)
x

array([1, 2, 3, 4, 5])

In [67]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])
x = np.union1d(arr1,arr2)
x

array([1, 2, 3, 4, 5, 6])

In [68]:
x = np.intersect1d(arr1,arr2)
x

array([3, 4])

In [70]:
## find only the values in the first set that is not present in the second set
newarr = np.setdiff1d(arr1,arr2,assume_unique=True)
newarr

array([1, 2])

In [71]:
## find only the values that are not present in both sets
newarr = np.setxor1d(arr1,arr2,assume_unique=True)
newarr

array([1, 2, 5, 6])